# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20170206_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album1',
            name='album1',
        ),
        migrations.RemoveField(
            model_name='song1',
            name='song1',
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='singer',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Album1',
        ),
        migrations.DeleteModel(
            name='Song1',
        ),
    ]
