# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20170207_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.Person'),
        ),
    ]
