# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:37
from __future__ import unicode_literals
from django.db import migrations, models


def add_persons(apps, schema_editor):

    Album = apps.get_model("music", "Album")
    Person = apps.get_model("music", "Person")
    Song = apps.get_model("music", "Song")

    for album, song in zip(Album.objects.all(), Song.objects.all()):
        print (album.author, album.person_id), (song.singer, song.person_id)

        same_name_persons = Person.objects.filter(name=album.author)
        for same in same_name_persons.all():
            print same.id, same.name

        #album.person = Person.objects.filter(name=album.author).first()
        #album.save()

        #song.person = Person.objects.filter(name=song.author).first()
        #song.save()


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='music.Album'),
        ),
        migrations.RunPython(add_persons, lambda x, y: None),

    ]
