# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 17:37
from __future__ import unicode_literals
from django.db import migrations, models


def add_persons(apps, schema_editor):

    Album = apps.get_model("music", "Album")
    Person = apps.get_model("music", "Person")

    for album in Album.objects.all():
        album.person = Person.objects.create(name=album.author)
        album.save()



class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='music.Album'),
        ),
        migrations.RunPython(add_persons),

    ]
